name: Alpha builds

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: Trass3r/setup-cpp@master

    - name: Update system
      run: |
        set -eux
        sudo apt update
        sudo apt install -y build-essential g++-mingw-w64-i686 libpng16-16
        cd /tmp && wget --no-verbose https://github.com/mstorsjo/llvm-mingw/releases/download/20230730/llvm-mingw-20230730-ucrt-ubuntu-20.04-x86_64.tar.xz
        cd /usr/local/ && sudo tar xf /tmp/llvm-mingw-*.tar.xz --strip-components=1 && rm /tmp/llvm-mingw-*.tar.xz

    - name: build gfx
      run: |
        set -eux
        BUILD_NUMBER=$(git rev-list --count HEAD)
        PACKAGE_SUFFIX=Alpha
        make -j`nproc` BUILD_NUMBER=$BUILD_NUMBER PACKAGE_SUFFIX=$PACKAGE_SUFFIX pkg-enginegfx

    - name: build
      run: |
        set -eux
        BUILD_NUMBER=$(git rev-list --count HEAD)
        PACKAGE_SUFFIX=Alpha
        make -j`nproc` BUILD_NUMBER=$BUILD_NUMBER PACKAGE_SUFFIX=$PACKAGE_SUFFIX heavylog DEBUG=1 -k
        make -j`nproc` BUILD_NUMBER=$BUILD_NUMBER PACKAGE_SUFFIX=$PACKAGE_SUFFIX standard
        make -j`nproc` BUILD_NUMBER=$BUILD_NUMBER PACKAGE_SUFFIX=$PACKAGE_SUFFIX package
        echo "ZIP_NAME=$(basename -s .7z pkg/keeperfx*.7z)" >> $GITHUB_ENV
        rm pkg/keeperfx*.7z
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ZIP_NAME }}
        path: pkg/**
